
/* Auto-generated by SynthetiCare Agent */
/* Program: 01_profiling */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/01_profiling.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/01_profiling.csv";


proc import datafile="/Users/drewwawrow/southlake/data/source_data.csv"
    out=WORK.SOURCE_DATA
    dbms=csv replace;
    guessingrows=max;
run;
proc contents data=WORK.SOURCE_DATA;
    title 'Dataset Contents';
run;
proc print data=WORK.SOURCE_DATA(obs=10);
    title 'First 10 Observations';
run;

proc means data=WORK.SOURCE_DATA n nmiss mean std min q1 median q3 max
           skewness kurtosis maxdec=4;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Descriptive Statistics — Numeric Variables';
    output out=WORK.PROFILE_STATS;
run;
proc univariate data=WORK.SOURCE_DATA normal;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    histogram / normal kernel;
    title 'Distribution Analysis with Normality Tests';
run;

proc freq data=WORK.SOURCE_DATA;
    tables municipality age_group sex income_quintile dwelling_type num_storeys population_segment / nocum;
    title 'Frequency Distributions — Categorical Variables';
run;

proc means data=WORK.SOURCE_DATA nmiss n;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Missing Value Analysis';
run;
proc means data=WORK.SOURCE_DATA p5 p10 p25 p50 p75 p90 p95 maxdec=4;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Percentile Analysis';
run;


ods csvall close;
ods html5 close;
ods listing;
