
/* Auto-generated by SynthetiCare Agent */
/* Program: 02_cleaning */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/02_cleaning.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/02_cleaning.csv";


proc stdize data=WORK.SOURCE_DATA out=WORK.CLEANED_DATA
    method=median reponly missing=median;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
run;

proc sql noprint;
    select municipality into :mode_municipality trimmed
    from WORK.SOURCE_DATA
    group by municipality
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(municipality) then municipality = "&mode_municipality";
run;

proc sql noprint;
    select age_group into :mode_age_group trimmed
    from WORK.SOURCE_DATA
    group by age_group
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(age_group) then age_group = "&mode_age_group";
run;

proc sql noprint;
    select sex into :mode_sex trimmed
    from WORK.SOURCE_DATA
    group by sex
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(sex) then sex = "&mode_sex";
run;

proc sql noprint;
    select income_quintile into :mode_income_quintile trimmed
    from WORK.SOURCE_DATA
    group by income_quintile
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(income_quintile) then income_quintile = "&mode_income_quintile";
run;

proc sql noprint;
    select dwelling_type into :mode_dwelling_type trimmed
    from WORK.SOURCE_DATA
    group by dwelling_type
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(dwelling_type) then dwelling_type = "&mode_dwelling_type";
run;

proc sql noprint;
    select num_storeys into :mode_num_storeys trimmed
    from WORK.SOURCE_DATA
    group by num_storeys
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(num_storeys) then num_storeys = "&mode_num_storeys";
run;

proc sql noprint;
    select population_segment into :mode_population_segment trimmed
    from WORK.SOURCE_DATA
    group by population_segment
    having count(*) = max(count(*));
quit;
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if missing(population_segment) then population_segment = "&mode_population_segment";
run;

proc means data=WORK.CLEANED_DATA n nmiss mean std min max maxdec=4;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Post-Cleaning Statistics';
run;

proc export data=WORK.CLEANED_DATA
    outfile="/Users/drewwawrow/southlake/output/cleaned_data.csv"
    dbms=csv replace;
run;


ods csvall close;
ods html5 close;
ods listing;
