
/* Auto-generated by SynthetiCare Agent */
/* Program: 02b_constraints */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/02b_constraints.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/02b_constraints.csv";


/* ============================================ */
/* Clinical Constraint Enforcement              */
/* ============================================ */
data WORK.CLEANED_DATA;
    set WORK.CLEANED_DATA;
    if age < 40 then has_dementia = 0;
    if age < 18 then do;
        has_hypertension = 0;
        has_copd = 0;
        has_arthritis = 0;
        has_heart_disease = 0;
        has_dementia = 0;
    end;
    chronic_condition_count = has_arthritis + has_asthma + has_copd + has_dementia + has_diabetes + has_heart_disease + has_hypertension + has_mood_disorders;
    if fall_risk_score < 0 then fall_risk_score = 0;
    if fall_risk_score > 1 then fall_risk_score = 1;
    if er_visits_12mo < 0 then er_visits_12mo = 0;
    if income < 0 then income = 0;
run;
proc means data=WORK.CLEANED_DATA n mean min max maxdec=4;
    var has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders chronic_condition_count
        fall_risk_score er_visits_12mo;
    title 'Post-Constraint Enforcement Statistics';
run;


ods csvall close;
ods html5 close;
ods listing;
