
/* Auto-generated by SynthetiCare Agent */
/* Program: 03_correlations */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/03_correlations.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/03_correlations.csv";


proc corr data=WORK.CLEANED_DATA pearson spearman nosimple
    outp=WORK.CORR_PEARSON outs=WORK.CORR_SPEARMAN;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Correlation Matrix — Pearson & Spearman';
run;
proc export data=WORK.CORR_PEARSON
    outfile="/Users/drewwawrow/southlake/output/correlation_matrix.csv"
    dbms=csv replace;
run;


ods csvall close;
ods html5 close;
ods listing;
