
/* Auto-generated by SynthetiCare Agent */
/* Program: 03b_risk_models */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/03b_risk_models.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/03b_risk_models.csv";

ods graphics on / width=800px height=500px;

data WORK.ANALYSIS;
    set WORK.CLEANED_DATA;
    er_high = (er_visits_12mo >= 3);
run;
proc logistic data=WORK.ANALYSIS descending;
    model er_high(event='1') = age income
        has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease
        / selection=stepwise slentry=0.05 slstay=0.05
          lackfit rsquare stb;
    title 'Logistic Regression — ER High Utilization Risk Factors';
run;

proc logistic data=WORK.CLEANED_DATA descending;
    model had_fall_12mo(event='1') = age has_mobility_limitation has_arthritis has_dementia has_stairs num_staircases
        / lackfit rsquare stb;
    title 'Logistic Regression — Fall Risk Factors';
run;
ods graphics off;

/* ============================================ */
/* Municipal Health Profiles                    */
/* Close-to-Home Care Planning                  */
/* ============================================ */
proc means data=WORK.CLEANED_DATA mean std median q1 q3 maxdec=3;
    class municipality;
    var age risk_score er_visits_12mo fall_risk_score chronic_condition_count income;
    output out=WORK.MUNICIPAL_PROFILES;
    title 'Municipal Health Profiles — Southlake Catchment';
run;
proc freq data=WORK.CLEANED_DATA;
    tables municipality * population_segment / chisq norow nocol;
    title 'Population Segments by Municipality';
run;

proc means data=WORK.CLEANED_DATA mean maxdec=4;
    class municipality;
    var has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation;
    title 'Condition Prevalence by Municipality';
run;

ods graphics on / width=900px height=500px;
proc sgplot data=WORK.CLEANED_DATA;
    vbar municipality / response=risk_score stat=mean
        fillattrs=(color=cx00838f) categoryorder=respdesc;
    title 'Average Risk Score by Municipality';
run;
proc sgplot data=WORK.CLEANED_DATA;
    vbar municipality / response=er_visits_12mo stat=mean
        fillattrs=(color=cx004d5a) categoryorder=respdesc;
    title 'Average ER Visits (12mo) by Municipality';
run;
proc sgplot data=WORK.CLEANED_DATA;
    vbar municipality / response=fall_risk_score stat=mean
        fillattrs=(color=cxe53935) categoryorder=respdesc;
    title 'Average Fall Risk Score by Municipality';
run;
ods graphics off;


ods csvall close;
ods html5 close;
ods listing;
