
/* Auto-generated by SynthetiCare Agent */
/* Program: 04_visualizations */
/* Timestamp: 2026-04-13 20:10:53 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/04_visualizations.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/04_visualizations.csv";

ods graphics on / width=800px height=500px;

proc sgplot data=WORK.CLEANED_DATA;
    histogram age / fillattrs=(color=cx00838f transparency=0.3);
    density age / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Age';
run;

proc sgplot data=WORK.CLEANED_DATA;
    histogram income / fillattrs=(color=cx00838f transparency=0.3);
    density income / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Income';
run;

proc sgplot data=WORK.CLEANED_DATA;
    histogram risk_score / fillattrs=(color=cx00838f transparency=0.3);
    density risk_score / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Risk Score';
run;

proc sgplot data=WORK.CLEANED_DATA;
    histogram chronic_condition_count / fillattrs=(color=cx00838f transparency=0.3);
    density chronic_condition_count / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Chronic Condition Count';
run;

proc sgplot data=WORK.CLEANED_DATA;
    histogram er_visits_12mo / fillattrs=(color=cx00838f transparency=0.3);
    density er_visits_12mo / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Er Visits 12Mo';
run;

proc sgplot data=WORK.CLEANED_DATA;
    histogram fall_risk_score / fillattrs=(color=cx00838f transparency=0.3);
    density fall_risk_score / type=kernel lineattrs=(color=cx004d5a thickness=2);
    title 'Distribution of Fall Risk Score';
run;

proc sgplot data=WORK.CLEANED_DATA;
    vbar municipality / response=risk_score stat=mean
        fillattrs=(color=cx00838f) categoryorder=respdesc;
    title 'Average Risk Score by Municipality';
run;
ods graphics off;


ods csvall close;
ods html5 close;
ods listing;
