
/* Auto-generated by SynthetiCare Agent */
/* Program: 05_fidelity */
/* Timestamp: 2026-04-13 20:11:06 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/05_fidelity.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/05_fidelity.csv";


proc import datafile="/Users/drewwawrow/southlake/output/synthetic_data.csv"
    out=WORK.SYNTHETIC_DATA dbms=csv replace;
    guessingrows=max;
run;

proc means data=WORK.CLEANED_DATA n mean std min max skewness kurtosis maxdec=4;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Original Data — Summary Statistics';
run;
proc means data=WORK.SYNTHETIC_DATA n mean std min max skewness kurtosis maxdec=4;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
    title 'Synthetic Data — Summary Statistics';
run;
proc corr data=WORK.CLEANED_DATA pearson nosimple outp=WORK.ORIG_CORR;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
run;
proc corr data=WORK.SYNTHETIC_DATA pearson nosimple outp=WORK.SYNTH_CORR;
    var age income has_stairs num_staircases num_rooms bmi physical_inactivity has_arthritis has_asthma has_copd has_dementia has_diabetes has_heart_disease has_hypertension has_mood_disorders has_mobility_limitation chronic_condition_count risk_score er_visits_12mo fall_risk_score had_fall_12mo;
run;
data WORK.COMBINED;
    set WORK.CLEANED_DATA(in=a) WORK.SYNTHETIC_DATA(in=b);
    if a then source='Original'; else source='Synthetic';
run;
ods graphics on / width=800px height=500px;

proc sgplot data=WORK.COMBINED;
    histogram age / group=source transparency=0.5;
    density age / type=kernel group=source;
    title 'Fidelity: Age';
run;

proc sgplot data=WORK.COMBINED;
    histogram risk_score / group=source transparency=0.5;
    density risk_score / type=kernel group=source;
    title 'Fidelity: Risk Score';
run;

proc sgplot data=WORK.COMBINED;
    histogram income / group=source transparency=0.5;
    density income / type=kernel group=source;
    title 'Fidelity: Income';
run;

proc sgplot data=WORK.COMBINED;
    histogram fall_risk_score / group=source transparency=0.5;
    density fall_risk_score / type=kernel group=source;
    title 'Fidelity: Fall Risk Score';
run;
ods graphics off;


ods csvall close;
ods html5 close;
ods listing;
