
/* Auto-generated by SynthetiCare Agent */
/* Program: 06_sas_synthetic */
/* Timestamp: 2026-04-13 20:11:06 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/06_sas_synthetic.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/06_sas_synthetic.csv";


/* ============================================ */
/* Synthetic Data Generation via SAS            */
/* Stratified Bootstrap + Perturbation          */
/* ============================================ */
proc surveyselect data=WORK.CLEANED_DATA
    out=WORK.BOOTSTRAP_SAMPLE
    method=urs n=10000 seed=42;
    strata municipality;
run;
data WORK.SYNTHETIC_DATA;
    set WORK.BOOTSTRAP_SAMPLE;
    age = round(age + rand('NORMAL', 0, 2));
    age = min(99, max(0, age));
    income = income * (1 + rand('NORMAL', 0, 0.08));
    income = max(0, round(income, 100));
    risk_score = risk_score + rand('NORMAL', 0, 3);
    risk_score = max(0, round(risk_score, 0.1));
    er_visits_12mo = max(0, round(er_visits_12mo + rand('NORMAL', 0, 0.5)));
    fall_risk_score = min(1.0, max(0,
        fall_risk_score + rand('NORMAL', 0, 0.05)));
    fall_risk_score = round(fall_risk_score, 0.001);
    if age < 40 then has_dementia = 0;
    if age < 18 then do;
        has_hypertension = 0; has_copd = 0;
        has_arthritis = 0; has_heart_disease = 0;
        has_dementia = 0;
    end;
    drop SelectionProb SamplingWeight;
run;
proc means data=WORK.SYNTHETIC_DATA n mean std min max maxdec=4;
    title 'Synthetic Data — Summary Statistics';
run;
proc export data=WORK.SYNTHETIC_DATA
    outfile="/Users/drewwawrow/southlake/output/synthetic_data_sas.csv"
    dbms=csv replace;
run;


ods csvall close;
ods html5 close;
ods listing;
