
/* Auto-generated by SynthetiCare Agent */
/* Program: 07_privacy_dcr */
/* Timestamp: 2026-04-13 20:11:06 */

ods listing close;
ods html5 file="/Users/drewwawrow/southlake/output/07_privacy_dcr.html"
         options(bitmap_mode='inline') style=HTMLBlue;
ods csvall file="/Users/drewwawrow/southlake/output/07_privacy_dcr.csv";


/* ============================================ */
/* Privacy: Distance to Closest Record (DCR)    */
/* ============================================ */
proc standard data=WORK.CLEANED_DATA(keep=age income risk_score)
    out=WORK.ORIG_STD mean=0 std=1;
    var age income risk_score;
run;
proc standard data=WORK.SYNTHETIC_DATA(keep=age income risk_score)
    out=WORK.SYNTH_STD mean=0 std=1;
    var age income risk_score;
run;
proc surveyselect data=WORK.SYNTH_STD out=WORK.SYNTH_SAMPLE
    n=500 method=srs seed=42;
run;
proc iml;
    use WORK.ORIG_STD;
    read all var {"age" "income" "risk_score"} into orig;
    close;
    use WORK.SYNTH_SAMPLE;
    read all var {"age" "income" "risk_score"} into synth;
    close;
    n_synth = nrow(synth);
    dcr = j(n_synth, 1,.);
    do i = 1 to n_synth;
        diffs = orig - repeat(synth[i,], nrow(orig), 1);
        dists = sqrt(diffs[,##]);
        dcr[i] = min(dists);
    end;
    median_dcr = median(dcr);
    p5_dcr = quantile(dcr, 0.05);
    p95_dcr = quantile(dcr, 0.95);
    print "=== Distance to Closest Record (DCR) ===" ,
          median_dcr[label="Median DCR"],
          p5_dcr[label="5th Percentile DCR"],
          p95_dcr[label="95th Percentile DCR"];
    if median_dcr < 0.5 then
        print "WARNING: Low DCR suggests potential memorization";
    else
        print "PASS: Synthetic records sufficiently distant from originals";
    create WORK.DCR_RESULTS var {dcr};
    append from dcr;
    close WORK.DCR_RESULTS;
quit;
proc univariate data=WORK.DCR_RESULTS;
    var dcr;
    histogram dcr / normal;
    title 'Distribution of Distance to Closest Record';
run;


ods csvall close;
ods html5 close;
ods listing;
